apiVersion: v1
kind: Service
metadata:
  name: shelly-exporter
  namespace: monitoring
spec:
  selector:
    app: shelly-exporter
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 2112
    targetPort: 2112