apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-prometheus
  namespace: external-monitoring
spec:
  parentRefs:
    - name: internal-gateway
      namespace: traefik
      kind: Gateway
      group: gateway.networking.k8s.io
  hostnames:
    - "external-prometheus.pawked.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: external-prometheus-server
          port: 80
          kind: Service
          group: ''
          weight: 1