apiVersion: v2
name: prometheus
description:  kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules combined with documentation and scripts to provide easy to operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.
type: application
version: 1.0.0
appVersion: v0.85.0
dependencies:
- name: kube-prometheus-stack
  version: 79.12.0
  repository: https://prometheus-community.github.io/helm-charts