apiVersion: v2
name: grafana
description: A Helm chart for Grafana
type: application
version: 1.1.0
appVersion: 12.1.1
dependencies:
  - name: grafana
    version: 10.4.1
    repository: https://grafana.github.io/helm-charts